# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!

target 'RxMoyaExample' do

  pod 'Moya-ModelMapper/RxSwift', '10.0.0-beta.1'
  pod 'RxCocoa', '~> 5'
  pod 'RxOptional'

end
